# Generated by Django 5.2.7 on 2026-02-05 10:25

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('xomashyo', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Nomi')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Tavsif')),
            ],
            options={
                'verbose_name': 'Kategoriya',
                'verbose_name_plural': 'Kategoriyalar',
            },
        ),
        migrations.CreateModel(
            name='ChiqimTuri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nomi')),
            ],
            options={
                'verbose_name': 'Chiqim turi',
                'verbose_name_plural': 'Chiqim turlari',
            },
        ),
        migrations.CreateModel(
            name='EskiIsh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mahsulot', models.CharField(max_length=500, null=True, verbose_name='Mahsulot')),
                ('sana', models.DateField(null=True, verbose_name='Sana')),
                ('narxi', models.IntegerField(null=True, verbose_name='Narxi')),
                ('soni', models.IntegerField(null=True, verbose_name='Soni')),
            ],
            options={
                'verbose_name': 'Eski ish',
                'verbose_name_plural': 'Eski ishlar',
            },
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='IshchiCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=50, verbose_name='Nomi')),
            ],
            options={
                'verbose_name': 'Ishchi turi',
                'verbose_name_plural': 'Ishchi turlari',
            },
        ),
        migrations.CreateModel(
            name='testmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Xaridor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=150, verbose_name='Ism')),
                ('telefon', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefon')),
                ('manzil', models.CharField(blank=True, max_length=255, null=True, verbose_name='Manzil')),
                ('izoh', models.TextField(blank=True, null=True, verbose_name='Izoh')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
            ],
            options={
                'verbose_name': 'Xaridor',
                'verbose_name_plural': 'Xaridorlar',
            },
        ),
        migrations.CreateModel(
            name='Chiqim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Nomi')),
                ('price', models.PositiveIntegerField(verbose_name='Narxi')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chiqimlar', to='crm.chiqimturi', verbose_name='Kategoriya')),
            ],
            options={
                'verbose_name': 'Chiqim',
                'verbose_name_plural': 'Chiqimlar',
            },
        ),
        migrations.CreateModel(
            name='Ishchi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=50, verbose_name='Ism')),
                ('familiya', models.CharField(max_length=50, verbose_name='Familiya')),
                ('maosh', models.IntegerField(verbose_name='Maosh')),
                ('telefon', models.CharField(max_length=15, verbose_name='Telefon')),
                ('is_oylik_open', models.BooleanField(default=True, null=True, verbose_name='Oylik ochiq')),
                ('yangi_oylik', models.IntegerField(default=0, null=True, verbose_name='Yangi oylik')),
                ('oylik_yopilgan_sana', models.DateField(auto_now=True, null=True, verbose_name='Oylik yopilgan sana')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('eski_ishlar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ishchilar', to='crm.eskiish', verbose_name='Eski ishlar')),
                ('turi', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ish_turi', to='crm.ishchicategory', verbose_name='Ish turi')),
            ],
            options={
                'verbose_name': 'Ishchi',
                'verbose_name_plural': 'Ishchilar',
            },
        ),
        migrations.CreateModel(
            name='Ish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soni', models.IntegerField(null=True, verbose_name='Soni')),
                ('sana', models.DateField(auto_now_add=True, null=True, verbose_name='Sana')),
                ('narxi', models.IntegerField(blank=True, null=True, verbose_name='Narxi')),
                ('status', models.CharField(blank=True, choices=[('yangi', 'Yangi'), ('yopilgan', 'Yopilgan')], max_length=30, null=True)),
                ('ishchi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ishlar', to='crm.ishchi', verbose_name='Ishchi')),
            ],
            options={
                'verbose_name': 'Ish',
                'verbose_name_plural': 'Ishlar',
            },
        ),
        migrations.AddField(
            model_name='eskiish',
            name='ishchi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.ishchi', verbose_name='Ishchi'),
        ),
        migrations.CreateModel(
            name='Avans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(blank=True, default=True, null=True, verbose_name='Aktivmi')),
                ('amount', models.PositiveIntegerField()),
                ('created', models.DateField(default=django.utils.timezone.now)),
                ('ended', models.DateField(blank=True, null=True, verbose_name='yopilgan sana')),
                ('ishchi', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crm.ishchi')),
            ],
        ),
        migrations.CreateModel(
            name='IshXomashyo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miqdor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Miqdor')),
                ('birlik_narx', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True, verbose_name='Birlik narxi')),
                ('qoshilgan_sana', models.DateTimeField(auto_now_add=True)),
                ('ish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ish_xomashyolar', to='crm.ish', verbose_name='Ish')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ish_xomashyolar', to='xomashyo.xomashyovariant', verbose_name='Variant')),
                ('xomashyo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ish_xomashyolar', to='xomashyo.xomashyo', verbose_name='Xomashyo')),
            ],
            options={
                'verbose_name': 'Ish xomashyosi',
                'verbose_name_plural': 'Ish xomashyolari',
                'ordering': ['-qoshilgan_sana'],
            },
        ),
        migrations.AddField(
            model_name='ish',
            name='xomashyolar',
            field=models.ManyToManyField(related_name='ishlar', through='crm.IshXomashyo', to='xomashyo.xomashyo', verbose_name='Xomashyolar'),
        ),
        migrations.CreateModel(
            name='Oyliklar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sana', models.DateField(default=django.utils.timezone.now, verbose_name='Sana')),
                ('oylik', models.IntegerField(null=True, verbose_name='Oylik')),
                ('yopilgan', models.BooleanField(default=False, verbose_name='Yopilgan')),
                ('ishchi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oyliklar', to='crm.ishchi', verbose_name='Ishchi')),
            ],
            options={
                'verbose_name': 'Oylik',
                'verbose_name_plural': 'Oyliklar',
            },
        ),
        migrations.AddField(
            model_name='ishchi',
            name='current_oylik',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_ishchi', to='crm.oyliklar', verbose_name='Joriy oylik'),
        ),
        migrations.AddField(
            model_name='eskiish',
            name='ishchi_oylik',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eski_ishlar', to='crm.oyliklar', verbose_name='Ishchi oylik'),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('new', 'Yangi'), ('bestseller', "Ko'p sotiladigan"), ('sale', 'Chegirma')], default='new', max_length=20, verbose_name='Holati')),
                ('nomi', models.CharField(max_length=255, verbose_name='Nomi')),
                ('description', models.TextField(verbose_name='Tavsif')),
                ('narxi', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Narxi')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Rasm')),
                ('avg_profit', models.PositiveIntegerField(default=0, verbose_name="O'rtacha foyda")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('narx_kosib', models.IntegerField(default=0, verbose_name='Kasb narxi')),
                ('narx_zakatovka', models.IntegerField(default=0, verbose_name='Zakatovka narxi')),
                ('narx_kroy', models.IntegerField(default=0, verbose_name='Kesish narxi')),
                ('narx_rezak', models.IntegerField(default=0, verbose_name='Rezak kesish narxi')),
                ('narx_pardoz', models.IntegerField(default=0, verbose_name='Pardoza narxi')),
                ('teri_sarfi', models.DecimalField(decimal_places=2, default=0, help_text='1 ta mahsulot uchun teri sarfi (kg, m2 yoki dona)', max_digits=10, verbose_name='Terı sarfi')),
                ('astar_sarfi', models.DecimalField(decimal_places=2, default=0, help_text='1 ta mahsulot uchun astar sarfi (kg, m2 yoki dona)', max_digits=10, verbose_name='Astar sarfi')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='crm.category', verbose_name='Kategoriya')),
            ],
            options={
                'verbose_name': 'Mahsulot',
                'verbose_name_plural': 'Mahsulotlar',
            },
        ),
        migrations.AddField(
            model_name='ish',
            name='mahsulot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.product', verbose_name='Mahsulot'),
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.PositiveIntegerField(default=0, null=True, verbose_name='Qoldiq')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Narxi')),
                ('image', models.ImageField(null=True, upload_to='product/', verbose_name='Rasm')),
                ('rang', models.CharField(blank=True, default='', max_length=50, verbose_name='Rang')),
                ('razmer', models.CharField(blank=True, default='', max_length=20, verbose_name='Razmer')),
                ('feature', models.ManyToManyField(blank=True, null=True, to='crm.feature')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='crm.product', verbose_name='Mahsulot')),
            ],
            options={
                'verbose_name': 'Mahsulot varianti',
                'verbose_name_plural': 'Mahsulot variantlari',
                'unique_together': {('product', 'rang')},
            },
        ),
        migrations.CreateModel(
            name='Sotuv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miqdor', models.PositiveIntegerField(verbose_name='Miqdor')),
                ('umumiy_summa', models.DecimalField(decimal_places=2, editable=False, max_digits=12, verbose_name='Umumiy summa')),
                ('sana', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Sana')),
                ('mahsulot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='crm.product', verbose_name='Mahsulot')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='crm.productvariant', verbose_name='Mahsulot variant')),
                ('xaridor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='crm.xaridor', verbose_name='Xaridor')),
            ],
            options={
                'verbose_name': 'Sotuv',
                'verbose_name_plural': 'Sotuvlar',
            },
        ),
        migrations.CreateModel(
            name='TeriSarfi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miqdor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Sarflangan miqdor')),
                ('sana', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Sana')),
                ('ish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teri_sarflari', to='crm.ish', verbose_name='Ish')),
                ('ishchi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teri_sarflari', to='crm.ishchi', verbose_name='Ishchi')),
                ('xomashyo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teri_sarflari', to='xomashyo.xomashyo', verbose_name='Teri')),
            ],
            options={
                'verbose_name': 'Teri sarfi',
                'verbose_name_plural': 'Teri sarflari',
                'ordering': ['-sana'],
            },
        ),
        migrations.CreateModel(
            name='Kirim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summa', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Summa')),
                ('sana', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Sana')),
                ('izoh', models.TextField(blank=True, null=True)),
                ('mahsulot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.product', verbose_name='Mahsulot')),
                ('sotuv', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kirim', to='crm.sotuv', verbose_name='Sotuv')),
                ('xaridor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.xaridor', verbose_name='Xaridor')),
            ],
            options={
                'verbose_name': 'Kirim',
                'verbose_name_plural': 'Kirimlar',
            },
        ),
    ]
