# Generated by Django 5.2.4 on 2025-11-04 18:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChiqimTuri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='EskiIsh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mahsulot', models.CharField(max_length=500, null=True)),
                ('sana', models.DateField(null=True)),
                ('narxi', models.IntegerField(null=True)),
                ('soni', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='IshchiCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Chiqim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('price', models.PositiveIntegerField()),
                ('created', models.DateField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chiqimlar', to='crm.chiqimturi')),
            ],
        ),
        migrations.CreateModel(
            name='Ishchi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=50)),
                ('familiya', models.CharField(max_length=50)),
                ('maosh', models.IntegerField()),
                ('telefon', models.CharField(max_length=15)),
                ('is_oylik_open', models.BooleanField(default=True, null=True)),
                ('yangi_oylik', models.IntegerField(default=0, null=True)),
                ('oylik_yopilgan_sana', models.DateField(auto_now=True, null=True)),
                ('eski_ishlar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ishchilar', to='crm.eskiish')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ishchi_profile', to=settings.AUTH_USER_MODEL)),
                ('turi', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ish_turi', to='crm.ishchicategory')),
            ],
        ),
        migrations.AddField(
            model_name='eskiish',
            name='ishchi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.ishchi'),
        ),
        migrations.CreateModel(
            name='Oyliklar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sana', models.DateField(default=django.utils.timezone.now)),
                ('oylik', models.IntegerField(null=True)),
                ('yopilgan', models.BooleanField(default=False)),
                ('ishchi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oyliklar', to='crm.ishchi')),
                ('ishlari', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='oylik_ishlari', to='crm.eskiish')),
            ],
        ),
        migrations.AddField(
            model_name='ishchi',
            name='current_oylik',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_ishchi', to='crm.oyliklar'),
        ),
        migrations.AddField(
            model_name='eskiish',
            name='ishchi_oylik',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eski_ishlar', to='crm.oyliklar'),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('new', 'New'), ('bestseller', 'Bestseller'), ('sale', 'Sale')], default='new', max_length=20)),
                ('nomi', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('narxi', models.DecimalField(decimal_places=2, max_digits=10)),
                ('soni', models.PositiveIntegerField()),
                ('image', models.ImageField(upload_to='products/')),
                ('avg_profit', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('narx_kosib', models.IntegerField(default=0)),
                ('narx_zakatovka', models.IntegerField(default=0)),
                ('narx_kroy', models.IntegerField(default=0)),
                ('narx_pardoz', models.IntegerField(default=0)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='crm.category')),
            ],
        ),
        migrations.CreateModel(
            name='Ish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soni', models.IntegerField(null=True)),
                ('sana', models.DateField(auto_now_add=True, null=True)),
                ('narxi', models.IntegerField(blank=True, null=True)),
                ('ishchi', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ishlar', to='crm.ishchi')),
                ('mahsulot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=10, null=True)),
                ('color', models.CharField(max_length=50, null=True)),
                ('stock', models.PositiveIntegerField(default=0, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('image', models.ImageField(null=True, upload_to='product/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='crm.product')),
            ],
        ),
    ]
