# Generated by Django 5.2.7 on 2025-11-08 17:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Xaridor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=150)),
                ('telefon', models.CharField(blank=True, max_length=20, null=True)),
                ('manzil', models.CharField(blank=True, max_length=255, null=True)),
                ('izoh', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sotuv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miqdor', models.PositiveIntegerField()),
                ('umumiy_summa', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('sana', models.DateTimeField(default=django.utils.timezone.now)),
                ('mahsulot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='crm.product')),
                ('xaridor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='crm.xaridor')),
            ],
        ),
        migrations.CreateModel(
            name='Kirim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summa', models.DecimalField(decimal_places=2, max_digits=12)),
                ('sana', models.DateTimeField(default=django.utils.timezone.now)),
                ('mahsulot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.product')),
                ('sotuv', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kirim', to='crm.sotuv')),
                ('xaridor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.xaridor')),
            ],
        ),
    ]
