# Generated by Django 5.2.7 on 2025-11-09 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_xaridor_sotuv_kirim'),
    ]

    operations = [
        migrations.AddField(
            model_name='ishchi',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
