# Generated by Django 5.2.7 on 2025-12-27 13:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='XomashyoCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Kategoriya nomi')),
                ('tavsif', models.TextField(blank=True, verbose_name='Tavsif')),
                ('tartib', models.IntegerField(default=0, verbose_name='Tartib raqami')),
                ('turi', models.CharField(choices=[('real', 'Real xomashyo'), ('process', 'Jarayon xomashyo')], default='real', max_length=20, verbose_name='Kategoriya turi')),
            ],
            options={
                'verbose_name': 'Xomashyo kategoriyasi',
                'verbose_name_plural': 'Xomashyo kategoriyalari',
                'ordering': ['tartib', 'name'],
            },
        ),
        migrations.CreateModel(
            name='YetkazibBeruvchi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=255)),
                ('telefon', models.CharField(max_length=20)),
                ('manzil', models.TextField()),
                ('inn', models.CharField(blank=True, max_length=20)),
                ('qisqacha_tavsif', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Xomashyo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=255)),
                ('rang', models.CharField(blank=True, max_length=50, null=True)),
                ('miqdori', models.DecimalField(decimal_places=2, max_digits=10)),
                ('olchov_birligi', models.CharField(choices=[('kg', 'Kilogramm'), ('gr', 'Gramm'), ('lt', 'Litr'), ('dona', 'Dona'), ('dm', 'detsimetr')], max_length=20)),
                ('minimal_miqdor', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('narxi', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('qabul_qilingan_sana', models.DateField(auto_now_add=True)),
                ('amal_qilish_muddati', models.DateField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('holati', models.CharField(choices=[('active', 'Faol'), ('deactive', 'Nofaol'), ('expired', 'Muddati otgan')], max_length=20)),
                ('qr_code', models.CharField(blank=True, max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='xomashyolar', to='xomashyo.xomashyocategory', verbose_name='Kategoriya')),
                ('yetkazib_beruvchi', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='xomashyo.yetkazibberuvchi')),
            ],
        ),
        migrations.CreateModel(
            name='XomashyoVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rang', models.CharField(blank=True, max_length=50, null=True)),
                ('qalinlik', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('partiya_kodi', models.CharField(blank=True, max_length=100)),
                ('miqdori', models.DecimalField(decimal_places=2, max_digits=10)),
                ('narxi', models.DecimalField(decimal_places=2, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('xomashyo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variantlar', to='xomashyo.xomashyo')),
                ('yetkazuvchi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='xomashyo.yetkazibberuvchi')),
            ],
            options={
                'verbose_name': 'Xomashyo varianti',
                'verbose_name_plural': 'Xomashyo variantlari',
            },
        ),
        migrations.CreateModel(
            name='XomashyoHarakat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('harakat_turi', models.CharField(choices=[('kirim', 'Kirim'), ('chiqim', 'Chiqim'), ('inventarizatsiya', 'Inventarizatsiya'), ('qaytarish', 'Qaytarish')], max_length=20)),
                ('miqdori', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sana', models.DateTimeField(auto_now_add=True)),
                ('foydalanuvchi', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('xomashyo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='xomashyo.xomashyo', verbose_name='Xomashyo')),
                ('xomashyo_variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='harakatlar', to='xomashyo.xomashyovariant')),
            ],
        ),
    ]
