# Generated by Django 5.2.7 on 2025-11-08 15:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Xomashyo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=255)),
                ('miqdori', models.DecimalField(decimal_places=2, max_digits=10)),
                ('olchov_birligi', models.CharField(choices=[('kg', 'Kilogramm'), ('gr', 'Gramm'), ('lt', 'Litr'), ('dona', 'Dona'), ('dm', 'detsimetr')], max_length=20)),
                ('minimal_miqdor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('narxi', models.DecimalField(decimal_places=2, max_digits=15)),
                ('qabul_qilingan_sana', models.DateField(auto_now_add=True)),
                ('amal_qilish_muddati', models.DateField(blank=True, null=True)),
                ('holati', models.CharField(choices=[('active', 'Faol'), ('deactive', 'Nofaol'), ('expired', 'Muddati otgan')], max_length=20)),
                ('qr_code', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='YetkazibBeruvchi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=255)),
                ('telefon', models.CharField(max_length=20)),
                ('manzil', models.TextField()),
                ('inn', models.CharField(blank=True, max_length=20)),
                ('qisqacha_tavsif', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='XomashyoHarakat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('harakat_turi', models.CharField(choices=[('kirim', 'Kirim'), ('chiqim', 'Chiqim'), ('inventarizatsiya', 'Inventarizatsiya'), ('qaytarish', 'Qaytarish')], max_length=20)),
                ('miqdori', models.DecimalField(decimal_places=2, max_digits=10)),
                ('izoh', models.TextField(blank=True)),
                ('sana', models.DateTimeField(auto_now_add=True)),
                ('narxi', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('foydalanuvchi', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('xomashyo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xomashyo.xomashyo')),
                ('yetkazib_beruvchi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='xomashyo.yetkazibberuvchi')),
            ],
        ),
        migrations.AddField(
            model_name='xomashyo',
            name='yetkazib_beruvchi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='xomashyo.yetkazibberuvchi'),
        ),
    ]
